### ISSUE TITLE
No such file or directory (os error 2)

### ISSUE THREAD

**Issue by blueray453** [chmln/sd#137]
I am using `sd 0.7.6`.

The directory tree looks like:

```
.
├── choose-test.adoc
├── choose-test (another copy).adoc
├── choose-test (copy).adoc
└── Untitled Folder
    ├── choose-test.adoc
    ├── choose-test (another copy).adoc
    └── choose-test (copy).adoc

1 directory, 6 files
```

The error looks like:

```
% sd 'before' 'after' "$(fd --type file)"
Error processing Untitled Folder/choose-test (another copy).adoc
Untitled Folder/choose-test (copy).adoc
Untitled Folder/choose-test.adoc
choose-test (another copy).adoc
choose-test (copy).adoc
choose-test.adoc: No such file or directory (os error 2)
```

**Comment by CosmicHorrorDev** [comment]
Thanks for the detailed report! The issue is that the output of `"$(fd --type file)"` gets passed as a single argument. I made a simple program that just prints the arguments it has received to demo

![image](https://github.com/chmln/sd/assets/30302768/0999bda4-45b6-424d-91d4-114fafe9c14b)

You can see that all of the files get passed as one large arg that contains newline characters which explains the error message (it's saying `Error processing {file}: No such file or ...`, there are just newlines within the file path)

---

Luckily #61 changed the example on the README to instead call `sd` through `fd`'s `--exec` flag which properly handles the path

I also noticed a couple ways that the error can be cleaned up, so #186 makes it so an error code and a more detailed message is returned when there are issues processing replacements

![image](https://github.com/chmln/sd/assets/30302768/3c7b5b5d-434e-47b2-ae87-ba9b5db27535)
