### ISSUE TITLE
Which regex flavour does sd use? 

### ISSUE THREAD

**Issue by blueray453** [chmln/sd#70]
Which regex flavour does sd use?

**Comment by Hrxn** [comment]
https://github.com/rust-lang/regex

**Comment by blueray453** [comment]
The regex you pointed to says:

> Its syntax is similar to Perl-style regular expressions, but lacks a few features like look around and backreferences.

However, sd doc shows something like:

`echo 'cargo +nightly watch' | sd '(\w+)\s+\+(\w+)\s+(\w+)' 'cmd: $1, channel: $2, subcmd: $3'`

Isn't it backreferencing? Am I missing something?

**Comment by Hrxn** [comment]
Well, that's a question I've asked myself before as well..

I think the problem is that "backreference" is used a bit ambiguously when it comes to regular expressions. Because Rust Regex definitely supports capture groups, and you can use named capture groups, as well as ("back-")referenced groups by number (just like in any other regular expressions implementation). The syntax in actual Rust code looks a bit different though, but if using any Rust program on the command-line (`sd`, or ripgrep, or whatever) you can address capture groups like in your example. It's probably just some internal alias or something, basically a bit of syntactic sugar.

What does not work, as far as I understand it, is using backreferences in the regex query itself, i.e. in your example `sd ' (\w+)\s+\+(\w+)\s+(\w+)`, this could also be expressed/reformatted as something like `(\w+)\s+\+\1\s+\1`, as far as I know.
And this will probably not work, I assume.

Not a loss, in my opinion. I've never used such a backreference. It's a bit shorter, but also makes the expression less readable. And they are often complex enough already.
